### ISSUE TITLE
Separate html code from typescript file

### ISSUE THREAD

**Issue by nirojdyola** [ole-vi/planet#20]
Make a separate html file for each component. Don;t include the html code in typescript file . It is just for structure maintaining so that easy to find the bug .

**Comment by paulbert** [comment]
Could you explain in more detail how this makes it easier to find bugs?  I think it's more easily maintainable to leave HTML in the typescript file for small templates because then you only have one file to work with when making changes.

**Comment by paulbert** [comment]
Also, adding this to the **planet alpha** project.  Please add all issues to this project, thanks!

**Comment by razu9861** [comment]
@paulbert we were moving html files to .html files sho that the comonents ts will look more clean, but if there are few lines of html codes like tables and fetchig data on tables, or creating buttons we can use components ts but for longer files it is easy to use .html

**Comment by paulbert** [comment]
@razu9861 @nirojdyola I think we should keep the HTML and SCSS in the `component.ts` file if there are fewer than 12 lines total OR if someone makes a good case for keeping it in.

At that length the HTML/SCSS still doesn't obscure the JavaScript, and we can keep a flatter folder structure with fewer files.

An example of what I'd call a good case is the `page-not-found` component because there is no JavaScript functionality in the component so the HTML in that case can stay in the `component.ts` file.  Since it's already in the repository as separate files, I don't think we need to change this now, though.

If that sounds good, then the one file that we should change is the `login.component.ts` to move its template into a `login.component.html` file.

**Comment by paulbert** [comment]
Closing this as most, if not all, files follow the style guide.
