### ISSUE TITLE
Can we have our backend connect to DB instead of our client via browser?

### ISSUE THREAD

**Issue by mappuji** [ole-vi/planet#76]
https://github.com/ole-vi/planet/blob/d80af984ba5df1a8e388cda8ccc6eb241ac7597c/src/app/shared/couchdb.service.ts#L12

1. Hardcoding stuff is not good, we need to create a config file
2. Can we abstracting away that the things that connect to DB is the backend not the client via their browser, so that we can have multiple domain?

**Comment by paulbert** [comment]
I would say not at this stage of development since to create a backend would be duplicating work already done for us with the `ng serve` command and the CouchDB API. @dogi if you disagree we can get working on a solution that would work for this.

1. We do have the Angular environment variables (as used for the port) available which change based on the build.  You're right that this shouldn't be hardcoded, but I also think rather than setting this in a configuration we could alternatively use the domain name the client is at as the default.  Unless you expect the domain/ip address of the app docker to be different from the CouchDB docker.

2. Having a backend "middleman" to handle which domain a request goes to isn't necessary on its own.  What are the scenarios you are thinking we need this for?  @dogi if you have any more detail please let me know.

**Comment by mappuji** [comment]
Sorry for not giving the clear explanation, but I can demonstrate it if you are in talk.

Here is the use cases:
* I setup nation on a server which has IP Address and/or domain.
* I access from outside so I use the domain, tada 🎉 I can't access since db is pointing to `127xxx`
* Our problem is the one who makes the `API Call` to CouchDB is our client in their browser not our app with internal link.
* Actually our Angular is a webs server, we should able to make internal link from our angular app to CouchDB instead of our client's browser do the call which is less secure and bound to the host declared in config or in the config file. If we can connect with internal link, it will be easier if we have multiple hostname.

**Comment by mappuji** [comment]
Solved by #81
